with-expecter: True
inpackage: True
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "mock_{{.InterfaceName | camelcase | firstLower}}_test.go"
#all: True
#recursive: True
packages:
  github.com/opplieam/bb-admin-api/internal/v1/user:
    interfaces:
      Storer:
  github.com/opplieam/bb-admin-api/internal/v1/category:
    interfaces:
      Storer: