apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-api-deployment
  namespace: buy-better
spec:
  selector:
    matchLabels:
      app: admin-api

  template:
    metadata:
      labels:
        app: admin-api

    spec:
      terminationGracePeriodSeconds: 60

      containers:
        - name: admin-api
          image: admin-api-image
          ports:
            - name: admin-api-port
              containerPort: 3000

          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
