apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/admin-api/
patches:
  - path: ./dev-service-patch.yaml
  - path: ./dev-deployment-patch.yaml
images:
  - name: admin-api-image
    newName: opplieam/bb-admin-api
    newTag: local-dev