name: Run unit test
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest
    environment: Github Action
    env:
      TOKEN_ENCODED: ${{ secrets.TOKEN_ENCODED }}

    steps:
      - name: echo
        run: echo "Token key ${{secrets.TOKEN_ENCODED}}"


      - name: Check out code
        uses: actions/checkout@v4

#      - name: Setup Go environment
#        uses: actions/setup-go@v5.0.2
#        with:
#          go-version: '1.22.2'
#
#      - name: Run unit test
#        run: make test-unit

