name: Run unit test
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/go-setup@v5
        with:
          go-version: 1.22.2
      - uses: actions/checkout@v4

      - name: Run unit test
        run: make test-unit

